cache:
  directories:
  - "$HOME/.gradle"
jdk:
- opendk8
addons:
  chrome: stable
  firefox: latest
jobs:
  include:
    - stage: tests
      script: 
        - cd complete
        - ./runtests.sh
        - cd ..
    - stage: build-guide
      script: ./travis-build.sh
    - stage: republish-guides
      script: ./republish-guides.sh      
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  global:
  - secure: sfp81JWETjvtlBtURM99cvAWYxKLOM+U0uczHSSob5m2DIEXyxy06mGuwqtOMwm+RBCkavtwKlpmQc6Va0H9M17ac9Vh55Rf/cAz+qxy7E2eZ5nYLuLFDWzK+e1JddYbVC/y/1RHg7WqqzqTjomIZVLhFgUMwhxv2Mz0wIRKkfOy1bWtvetHeDHCcidex0mYt++gcnTV1iE0ByytbZ9HdnMbqm1ju2IPlAsw0Pc5X4ZBngOZMnnXlwJ1uDRjlL+GGcNJ6DqNxfAv9BK8xZklNzJd3UsBWRNaEyYg0NI+S0zaoRkvZfdjvFwPXXFZdAH5z3hnVk7ufyhUN6XmtIN4cjGWn3kjpXyDf0MEG05+M5ZTIdOUxVl/V64v77bo8DsgJySSDBu4r8Q1Glo4se3CKIX816MhZduTBSxWT47S4uUtV98RMSj41KRl6t6DrUW2kWbQXd04TZvqLahdoC3JuJ2I+lejQk2MvUNyuiMq4Bkqn4KiuVG6mVU8Kmn7Sj0eRDsy0krnSPmddZfjnT6r7cLeo5IRYdbOcz4lHZ8u+5aNeaxpQPNUS1cBi8KzhhqFWLv2uS8I1zMlKzXNqrYiuEiIa1XGlrcFM109saK6QmeD3YTMrlguYE/t9GuF4g/OtVRVTO5dOmfDmhrdmjcqu/sxqQqELzN/M7giwh1F5BY=
  - secure: UBCjyoGtOr8KGn/N7Ekx4H78xJ71zsx0fsPk4GlC85IOA6zpix1xDTsZjqIDTFkP5LR/LBvHS6u+wJDRhy5cWidylYyBwZcRdi84LuI+SZe7tpZtw/IMC1bNpTxJbbD9zhT/m8gFKrugga5MJ6LgNF9nU/WV7wetX+rZu88QtX1uyLyBq9tpiXYNyNyC7KqaJ7jSjWHictGPerqid/5Tf1yzNaRMjpQvWBVsY3P3jvqwpa1YXY1AOEHxP7O9AuS065iTZ26x8ol6XXU7zDLIM+IBhsZzzSp2xVcNTSEMtMjxB1B58gOuCEPYtuRjm3dSbYNJK35d2qcbRRYQQpgzGj1i8ovbYENK3dd1Jbxbm5Q/CjHYfXiJ4YG9rWMS9His1fr/4d+gsCBexJlrJB7Y75R4xLpWR0CeYrUJ1wM6n1lia7u0R7AbP3VF/Envh1mLpf9xuiJRAWldDDS2+ls48sNtxCEKIMHqyVoyWEdhTmLIqbzR7yuDoIxKY98XKXvyn8e42CuaypRT+y7kK3xseIokforQsCF7ybOeoIYF0b1M6mXq1l1gq/LOXWeV9T8AKr6/pmcDQqEOqQ4uezvrLiULJBKBG3CNMhHm+jKRqGkuxQHOfITz5T9MzMis1u1W/9lgDEZa1ZTtGu4wQQXUd42RQB7xNjJ+WP+IlA8FxSU=
  - secure: hITnSEuFBCSV5Cwh0q7DYf53kq4pTpYAJHcz2r3KSUeUq+NJfh4qK1HWc02KqHH/jEPnKH3TH9A8sCkFOrkwmg7EmMqQu/1vuuQtOqRsVVodJOmIXOI6iXm466yfLLigDFPyDUsiy655YgtCmAEHIqLBirtfLPkeDYQAKheTQkXAkwIboVUGjA3MJu2VaIVA0P92G0QNsSNyPmbI3oixyhlWD65C9pTblVLkKGh0h4QmW0ccBu6N6A+6TisXC49SNAldEi6yrXh4FP9qitIz261/XACnPAfDY0yPy/2NhJrxPj1g6uYO5KH8KJf2fPmHtNf0NMC05nYinK+cZcbpIw3h0rYowgwY3iULXy9JG+w7TboZ+IPrpSQNqgg4AUUAJ0AQ4Acs22OEv+yN6JtxN1oxG0RsSh6Lv0b8MHXzx7s6RdQpZ2vJqmIyYPu4Oqu7ur/QJAoSO0iVFFLmk3wxKXhW0kByfnk8lyK4q1OhIp02MVpMEHAGzOb90FLvLodX6x4rxV5xAwYPFXP8IqMWFoxAtwQebRnVU3bCWUPN8QS/SmCpIDGC06j2XDyfaUTJymBy6qnQy8431U7Qqg9vy5nCe+mhlQVuW/x2C8fD66mDA7bFsr9C9RwQ+f0m+IMmOrt2UL13FRSOsx5d9GxLDAkW6kyXTA3Z2Rj2DUHfH7w=
